spring:
  application:
    name: authorization
management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
  endpoints:
    web:
      base-path: /management
