spring:
  datasource:
    url: jdbc:h2:mem:db;;NON_KEYWORDS=authorization;INIT=CREATE SCHEMA IF NOT EXISTS oauth2
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: oauth2
  sql:
    init:
      mode: always
      schema-locations: "classpath:db/schema.sql"
      data-locations: "classpath:db/data.sql"
