spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com:
      developingforfun:
        authorization: DEBUG
security:
  jwt:
    keystore-file: server.jks
    alias: server
    keystore-password: password
